# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/VideoTags

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/VideoTags

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/VideoTags/CMakeFiles /home/pi/VideoTags/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/VideoTags/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VideoTags

# Build rule for target.
VideoTags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VideoTags
.PHONY : VideoTags

# fast build rule for target.
VideoTags/fast:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/build
.PHONY : VideoTags/fast

Source/src/VideoTag.o: Source/src/VideoTag.cpp.o
.PHONY : Source/src/VideoTag.o

# target to build an object file
Source/src/VideoTag.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/Source/src/VideoTag.cpp.o
.PHONY : Source/src/VideoTag.cpp.o

Source/src/VideoTag.i: Source/src/VideoTag.cpp.i
.PHONY : Source/src/VideoTag.i

# target to preprocess a source file
Source/src/VideoTag.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/Source/src/VideoTag.cpp.i
.PHONY : Source/src/VideoTag.cpp.i

Source/src/VideoTag.s: Source/src/VideoTag.cpp.s
.PHONY : Source/src/VideoTag.s

# target to generate assembly for a file
Source/src/VideoTag.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/Source/src/VideoTag.cpp.s
.PHONY : Source/src/VideoTag.cpp.s

home/pi/deps/AprilTags/Edge.o: home/pi/deps/AprilTags/Edge.cc.o
.PHONY : home/pi/deps/AprilTags/Edge.o

# target to build an object file
home/pi/deps/AprilTags/Edge.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Edge.cc.o
.PHONY : home/pi/deps/AprilTags/Edge.cc.o

home/pi/deps/AprilTags/Edge.i: home/pi/deps/AprilTags/Edge.cc.i
.PHONY : home/pi/deps/AprilTags/Edge.i

# target to preprocess a source file
home/pi/deps/AprilTags/Edge.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Edge.cc.i
.PHONY : home/pi/deps/AprilTags/Edge.cc.i

home/pi/deps/AprilTags/Edge.s: home/pi/deps/AprilTags/Edge.cc.s
.PHONY : home/pi/deps/AprilTags/Edge.s

# target to generate assembly for a file
home/pi/deps/AprilTags/Edge.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Edge.cc.s
.PHONY : home/pi/deps/AprilTags/Edge.cc.s

home/pi/deps/AprilTags/FloatImage.o: home/pi/deps/AprilTags/FloatImage.cc.o
.PHONY : home/pi/deps/AprilTags/FloatImage.o

# target to build an object file
home/pi/deps/AprilTags/FloatImage.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/FloatImage.cc.o
.PHONY : home/pi/deps/AprilTags/FloatImage.cc.o

home/pi/deps/AprilTags/FloatImage.i: home/pi/deps/AprilTags/FloatImage.cc.i
.PHONY : home/pi/deps/AprilTags/FloatImage.i

# target to preprocess a source file
home/pi/deps/AprilTags/FloatImage.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/FloatImage.cc.i
.PHONY : home/pi/deps/AprilTags/FloatImage.cc.i

home/pi/deps/AprilTags/FloatImage.s: home/pi/deps/AprilTags/FloatImage.cc.s
.PHONY : home/pi/deps/AprilTags/FloatImage.s

# target to generate assembly for a file
home/pi/deps/AprilTags/FloatImage.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/FloatImage.cc.s
.PHONY : home/pi/deps/AprilTags/FloatImage.cc.s

home/pi/deps/AprilTags/GLine2D.o: home/pi/deps/AprilTags/GLine2D.cc.o
.PHONY : home/pi/deps/AprilTags/GLine2D.o

# target to build an object file
home/pi/deps/AprilTags/GLine2D.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GLine2D.cc.o
.PHONY : home/pi/deps/AprilTags/GLine2D.cc.o

home/pi/deps/AprilTags/GLine2D.i: home/pi/deps/AprilTags/GLine2D.cc.i
.PHONY : home/pi/deps/AprilTags/GLine2D.i

# target to preprocess a source file
home/pi/deps/AprilTags/GLine2D.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GLine2D.cc.i
.PHONY : home/pi/deps/AprilTags/GLine2D.cc.i

home/pi/deps/AprilTags/GLine2D.s: home/pi/deps/AprilTags/GLine2D.cc.s
.PHONY : home/pi/deps/AprilTags/GLine2D.s

# target to generate assembly for a file
home/pi/deps/AprilTags/GLine2D.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GLine2D.cc.s
.PHONY : home/pi/deps/AprilTags/GLine2D.cc.s

home/pi/deps/AprilTags/GLineSegment2D.o: home/pi/deps/AprilTags/GLineSegment2D.cc.o
.PHONY : home/pi/deps/AprilTags/GLineSegment2D.o

# target to build an object file
home/pi/deps/AprilTags/GLineSegment2D.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GLineSegment2D.cc.o
.PHONY : home/pi/deps/AprilTags/GLineSegment2D.cc.o

home/pi/deps/AprilTags/GLineSegment2D.i: home/pi/deps/AprilTags/GLineSegment2D.cc.i
.PHONY : home/pi/deps/AprilTags/GLineSegment2D.i

# target to preprocess a source file
home/pi/deps/AprilTags/GLineSegment2D.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GLineSegment2D.cc.i
.PHONY : home/pi/deps/AprilTags/GLineSegment2D.cc.i

home/pi/deps/AprilTags/GLineSegment2D.s: home/pi/deps/AprilTags/GLineSegment2D.cc.s
.PHONY : home/pi/deps/AprilTags/GLineSegment2D.s

# target to generate assembly for a file
home/pi/deps/AprilTags/GLineSegment2D.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GLineSegment2D.cc.s
.PHONY : home/pi/deps/AprilTags/GLineSegment2D.cc.s

home/pi/deps/AprilTags/Gaussian.o: home/pi/deps/AprilTags/Gaussian.cc.o
.PHONY : home/pi/deps/AprilTags/Gaussian.o

# target to build an object file
home/pi/deps/AprilTags/Gaussian.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Gaussian.cc.o
.PHONY : home/pi/deps/AprilTags/Gaussian.cc.o

home/pi/deps/AprilTags/Gaussian.i: home/pi/deps/AprilTags/Gaussian.cc.i
.PHONY : home/pi/deps/AprilTags/Gaussian.i

# target to preprocess a source file
home/pi/deps/AprilTags/Gaussian.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Gaussian.cc.i
.PHONY : home/pi/deps/AprilTags/Gaussian.cc.i

home/pi/deps/AprilTags/Gaussian.s: home/pi/deps/AprilTags/Gaussian.cc.s
.PHONY : home/pi/deps/AprilTags/Gaussian.s

# target to generate assembly for a file
home/pi/deps/AprilTags/Gaussian.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Gaussian.cc.s
.PHONY : home/pi/deps/AprilTags/Gaussian.cc.s

home/pi/deps/AprilTags/GrayModel.o: home/pi/deps/AprilTags/GrayModel.cc.o
.PHONY : home/pi/deps/AprilTags/GrayModel.o

# target to build an object file
home/pi/deps/AprilTags/GrayModel.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GrayModel.cc.o
.PHONY : home/pi/deps/AprilTags/GrayModel.cc.o

home/pi/deps/AprilTags/GrayModel.i: home/pi/deps/AprilTags/GrayModel.cc.i
.PHONY : home/pi/deps/AprilTags/GrayModel.i

# target to preprocess a source file
home/pi/deps/AprilTags/GrayModel.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GrayModel.cc.i
.PHONY : home/pi/deps/AprilTags/GrayModel.cc.i

home/pi/deps/AprilTags/GrayModel.s: home/pi/deps/AprilTags/GrayModel.cc.s
.PHONY : home/pi/deps/AprilTags/GrayModel.s

# target to generate assembly for a file
home/pi/deps/AprilTags/GrayModel.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/GrayModel.cc.s
.PHONY : home/pi/deps/AprilTags/GrayModel.cc.s

home/pi/deps/AprilTags/Homography33.o: home/pi/deps/AprilTags/Homography33.cc.o
.PHONY : home/pi/deps/AprilTags/Homography33.o

# target to build an object file
home/pi/deps/AprilTags/Homography33.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Homography33.cc.o
.PHONY : home/pi/deps/AprilTags/Homography33.cc.o

home/pi/deps/AprilTags/Homography33.i: home/pi/deps/AprilTags/Homography33.cc.i
.PHONY : home/pi/deps/AprilTags/Homography33.i

# target to preprocess a source file
home/pi/deps/AprilTags/Homography33.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Homography33.cc.i
.PHONY : home/pi/deps/AprilTags/Homography33.cc.i

home/pi/deps/AprilTags/Homography33.s: home/pi/deps/AprilTags/Homography33.cc.s
.PHONY : home/pi/deps/AprilTags/Homography33.s

# target to generate assembly for a file
home/pi/deps/AprilTags/Homography33.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Homography33.cc.s
.PHONY : home/pi/deps/AprilTags/Homography33.cc.s

home/pi/deps/AprilTags/MathUtil.o: home/pi/deps/AprilTags/MathUtil.cc.o
.PHONY : home/pi/deps/AprilTags/MathUtil.o

# target to build an object file
home/pi/deps/AprilTags/MathUtil.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/MathUtil.cc.o
.PHONY : home/pi/deps/AprilTags/MathUtil.cc.o

home/pi/deps/AprilTags/MathUtil.i: home/pi/deps/AprilTags/MathUtil.cc.i
.PHONY : home/pi/deps/AprilTags/MathUtil.i

# target to preprocess a source file
home/pi/deps/AprilTags/MathUtil.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/MathUtil.cc.i
.PHONY : home/pi/deps/AprilTags/MathUtil.cc.i

home/pi/deps/AprilTags/MathUtil.s: home/pi/deps/AprilTags/MathUtil.cc.s
.PHONY : home/pi/deps/AprilTags/MathUtil.s

# target to generate assembly for a file
home/pi/deps/AprilTags/MathUtil.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/MathUtil.cc.s
.PHONY : home/pi/deps/AprilTags/MathUtil.cc.s

home/pi/deps/AprilTags/Quad.o: home/pi/deps/AprilTags/Quad.cc.o
.PHONY : home/pi/deps/AprilTags/Quad.o

# target to build an object file
home/pi/deps/AprilTags/Quad.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Quad.cc.o
.PHONY : home/pi/deps/AprilTags/Quad.cc.o

home/pi/deps/AprilTags/Quad.i: home/pi/deps/AprilTags/Quad.cc.i
.PHONY : home/pi/deps/AprilTags/Quad.i

# target to preprocess a source file
home/pi/deps/AprilTags/Quad.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Quad.cc.i
.PHONY : home/pi/deps/AprilTags/Quad.cc.i

home/pi/deps/AprilTags/Quad.s: home/pi/deps/AprilTags/Quad.cc.s
.PHONY : home/pi/deps/AprilTags/Quad.s

# target to generate assembly for a file
home/pi/deps/AprilTags/Quad.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Quad.cc.s
.PHONY : home/pi/deps/AprilTags/Quad.cc.s

home/pi/deps/AprilTags/Segment.o: home/pi/deps/AprilTags/Segment.cc.o
.PHONY : home/pi/deps/AprilTags/Segment.o

# target to build an object file
home/pi/deps/AprilTags/Segment.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Segment.cc.o
.PHONY : home/pi/deps/AprilTags/Segment.cc.o

home/pi/deps/AprilTags/Segment.i: home/pi/deps/AprilTags/Segment.cc.i
.PHONY : home/pi/deps/AprilTags/Segment.i

# target to preprocess a source file
home/pi/deps/AprilTags/Segment.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Segment.cc.i
.PHONY : home/pi/deps/AprilTags/Segment.cc.i

home/pi/deps/AprilTags/Segment.s: home/pi/deps/AprilTags/Segment.cc.s
.PHONY : home/pi/deps/AprilTags/Segment.s

# target to generate assembly for a file
home/pi/deps/AprilTags/Segment.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/Segment.cc.s
.PHONY : home/pi/deps/AprilTags/Segment.cc.s

home/pi/deps/AprilTags/TagDetection.o: home/pi/deps/AprilTags/TagDetection.cc.o
.PHONY : home/pi/deps/AprilTags/TagDetection.o

# target to build an object file
home/pi/deps/AprilTags/TagDetection.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagDetection.cc.o
.PHONY : home/pi/deps/AprilTags/TagDetection.cc.o

home/pi/deps/AprilTags/TagDetection.i: home/pi/deps/AprilTags/TagDetection.cc.i
.PHONY : home/pi/deps/AprilTags/TagDetection.i

# target to preprocess a source file
home/pi/deps/AprilTags/TagDetection.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagDetection.cc.i
.PHONY : home/pi/deps/AprilTags/TagDetection.cc.i

home/pi/deps/AprilTags/TagDetection.s: home/pi/deps/AprilTags/TagDetection.cc.s
.PHONY : home/pi/deps/AprilTags/TagDetection.s

# target to generate assembly for a file
home/pi/deps/AprilTags/TagDetection.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagDetection.cc.s
.PHONY : home/pi/deps/AprilTags/TagDetection.cc.s

home/pi/deps/AprilTags/TagDetector.o: home/pi/deps/AprilTags/TagDetector.cc.o
.PHONY : home/pi/deps/AprilTags/TagDetector.o

# target to build an object file
home/pi/deps/AprilTags/TagDetector.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagDetector.cc.o
.PHONY : home/pi/deps/AprilTags/TagDetector.cc.o

home/pi/deps/AprilTags/TagDetector.i: home/pi/deps/AprilTags/TagDetector.cc.i
.PHONY : home/pi/deps/AprilTags/TagDetector.i

# target to preprocess a source file
home/pi/deps/AprilTags/TagDetector.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagDetector.cc.i
.PHONY : home/pi/deps/AprilTags/TagDetector.cc.i

home/pi/deps/AprilTags/TagDetector.s: home/pi/deps/AprilTags/TagDetector.cc.s
.PHONY : home/pi/deps/AprilTags/TagDetector.s

# target to generate assembly for a file
home/pi/deps/AprilTags/TagDetector.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagDetector.cc.s
.PHONY : home/pi/deps/AprilTags/TagDetector.cc.s

home/pi/deps/AprilTags/TagFamily.o: home/pi/deps/AprilTags/TagFamily.cc.o
.PHONY : home/pi/deps/AprilTags/TagFamily.o

# target to build an object file
home/pi/deps/AprilTags/TagFamily.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagFamily.cc.o
.PHONY : home/pi/deps/AprilTags/TagFamily.cc.o

home/pi/deps/AprilTags/TagFamily.i: home/pi/deps/AprilTags/TagFamily.cc.i
.PHONY : home/pi/deps/AprilTags/TagFamily.i

# target to preprocess a source file
home/pi/deps/AprilTags/TagFamily.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagFamily.cc.i
.PHONY : home/pi/deps/AprilTags/TagFamily.cc.i

home/pi/deps/AprilTags/TagFamily.s: home/pi/deps/AprilTags/TagFamily.cc.s
.PHONY : home/pi/deps/AprilTags/TagFamily.s

# target to generate assembly for a file
home/pi/deps/AprilTags/TagFamily.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/TagFamily.cc.s
.PHONY : home/pi/deps/AprilTags/TagFamily.cc.s

home/pi/deps/AprilTags/UnionFindSimple.o: home/pi/deps/AprilTags/UnionFindSimple.cc.o
.PHONY : home/pi/deps/AprilTags/UnionFindSimple.o

# target to build an object file
home/pi/deps/AprilTags/UnionFindSimple.cc.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/UnionFindSimple.cc.o
.PHONY : home/pi/deps/AprilTags/UnionFindSimple.cc.o

home/pi/deps/AprilTags/UnionFindSimple.i: home/pi/deps/AprilTags/UnionFindSimple.cc.i
.PHONY : home/pi/deps/AprilTags/UnionFindSimple.i

# target to preprocess a source file
home/pi/deps/AprilTags/UnionFindSimple.cc.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/UnionFindSimple.cc.i
.PHONY : home/pi/deps/AprilTags/UnionFindSimple.cc.i

home/pi/deps/AprilTags/UnionFindSimple.s: home/pi/deps/AprilTags/UnionFindSimple.cc.s
.PHONY : home/pi/deps/AprilTags/UnionFindSimple.s

# target to generate assembly for a file
home/pi/deps/AprilTags/UnionFindSimple.cc.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/AprilTags/UnionFindSimple.cc.s
.PHONY : home/pi/deps/AprilTags/UnionFindSimple.cc.s

home/pi/deps/adt/source/src/Acceleration.o: home/pi/deps/adt/source/src/Acceleration.cpp.o
.PHONY : home/pi/deps/adt/source/src/Acceleration.o

# target to build an object file
home/pi/deps/adt/source/src/Acceleration.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Acceleration.cpp.o
.PHONY : home/pi/deps/adt/source/src/Acceleration.cpp.o

home/pi/deps/adt/source/src/Acceleration.i: home/pi/deps/adt/source/src/Acceleration.cpp.i
.PHONY : home/pi/deps/adt/source/src/Acceleration.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Acceleration.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Acceleration.cpp.i
.PHONY : home/pi/deps/adt/source/src/Acceleration.cpp.i

home/pi/deps/adt/source/src/Acceleration.s: home/pi/deps/adt/source/src/Acceleration.cpp.s
.PHONY : home/pi/deps/adt/source/src/Acceleration.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Acceleration.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Acceleration.cpp.s
.PHONY : home/pi/deps/adt/source/src/Acceleration.cpp.s

home/pi/deps/adt/source/src/Angle.o: home/pi/deps/adt/source/src/Angle.cpp.o
.PHONY : home/pi/deps/adt/source/src/Angle.o

# target to build an object file
home/pi/deps/adt/source/src/Angle.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Angle.cpp.o
.PHONY : home/pi/deps/adt/source/src/Angle.cpp.o

home/pi/deps/adt/source/src/Angle.i: home/pi/deps/adt/source/src/Angle.cpp.i
.PHONY : home/pi/deps/adt/source/src/Angle.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Angle.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Angle.cpp.i
.PHONY : home/pi/deps/adt/source/src/Angle.cpp.i

home/pi/deps/adt/source/src/Angle.s: home/pi/deps/adt/source/src/Angle.cpp.s
.PHONY : home/pi/deps/adt/source/src/Angle.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Angle.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Angle.cpp.s
.PHONY : home/pi/deps/adt/source/src/Angle.cpp.s

home/pi/deps/adt/source/src/Attitude.o: home/pi/deps/adt/source/src/Attitude.cpp.o
.PHONY : home/pi/deps/adt/source/src/Attitude.o

# target to build an object file
home/pi/deps/adt/source/src/Attitude.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Attitude.cpp.o
.PHONY : home/pi/deps/adt/source/src/Attitude.cpp.o

home/pi/deps/adt/source/src/Attitude.i: home/pi/deps/adt/source/src/Attitude.cpp.i
.PHONY : home/pi/deps/adt/source/src/Attitude.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Attitude.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Attitude.cpp.i
.PHONY : home/pi/deps/adt/source/src/Attitude.cpp.i

home/pi/deps/adt/source/src/Attitude.s: home/pi/deps/adt/source/src/Attitude.cpp.s
.PHONY : home/pi/deps/adt/source/src/Attitude.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Attitude.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Attitude.cpp.s
.PHONY : home/pi/deps/adt/source/src/Attitude.cpp.s

home/pi/deps/adt/source/src/Box.o: home/pi/deps/adt/source/src/Box.cpp.o
.PHONY : home/pi/deps/adt/source/src/Box.o

# target to build an object file
home/pi/deps/adt/source/src/Box.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Box.cpp.o
.PHONY : home/pi/deps/adt/source/src/Box.cpp.o

home/pi/deps/adt/source/src/Box.i: home/pi/deps/adt/source/src/Box.cpp.i
.PHONY : home/pi/deps/adt/source/src/Box.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Box.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Box.cpp.i
.PHONY : home/pi/deps/adt/source/src/Box.cpp.i

home/pi/deps/adt/source/src/Box.s: home/pi/deps/adt/source/src/Box.cpp.s
.PHONY : home/pi/deps/adt/source/src/Box.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Box.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Box.cpp.s
.PHONY : home/pi/deps/adt/source/src/Box.cpp.s

home/pi/deps/adt/source/src/Coordinate.o: home/pi/deps/adt/source/src/Coordinate.cpp.o
.PHONY : home/pi/deps/adt/source/src/Coordinate.o

# target to build an object file
home/pi/deps/adt/source/src/Coordinate.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Coordinate.cpp.o
.PHONY : home/pi/deps/adt/source/src/Coordinate.cpp.o

home/pi/deps/adt/source/src/Coordinate.i: home/pi/deps/adt/source/src/Coordinate.cpp.i
.PHONY : home/pi/deps/adt/source/src/Coordinate.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Coordinate.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Coordinate.cpp.i
.PHONY : home/pi/deps/adt/source/src/Coordinate.cpp.i

home/pi/deps/adt/source/src/Coordinate.s: home/pi/deps/adt/source/src/Coordinate.cpp.s
.PHONY : home/pi/deps/adt/source/src/Coordinate.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Coordinate.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Coordinate.cpp.s
.PHONY : home/pi/deps/adt/source/src/Coordinate.cpp.s

home/pi/deps/adt/source/src/Duration.o: home/pi/deps/adt/source/src/Duration.cpp.o
.PHONY : home/pi/deps/adt/source/src/Duration.o

# target to build an object file
home/pi/deps/adt/source/src/Duration.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Duration.cpp.o
.PHONY : home/pi/deps/adt/source/src/Duration.cpp.o

home/pi/deps/adt/source/src/Duration.i: home/pi/deps/adt/source/src/Duration.cpp.i
.PHONY : home/pi/deps/adt/source/src/Duration.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Duration.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Duration.cpp.i
.PHONY : home/pi/deps/adt/source/src/Duration.cpp.i

home/pi/deps/adt/source/src/Duration.s: home/pi/deps/adt/source/src/Duration.cpp.s
.PHONY : home/pi/deps/adt/source/src/Duration.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Duration.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Duration.cpp.s
.PHONY : home/pi/deps/adt/source/src/Duration.cpp.s

home/pi/deps/adt/source/src/Force.o: home/pi/deps/adt/source/src/Force.cpp.o
.PHONY : home/pi/deps/adt/source/src/Force.o

# target to build an object file
home/pi/deps/adt/source/src/Force.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Force.cpp.o
.PHONY : home/pi/deps/adt/source/src/Force.cpp.o

home/pi/deps/adt/source/src/Force.i: home/pi/deps/adt/source/src/Force.cpp.i
.PHONY : home/pi/deps/adt/source/src/Force.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Force.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Force.cpp.i
.PHONY : home/pi/deps/adt/source/src/Force.cpp.i

home/pi/deps/adt/source/src/Force.s: home/pi/deps/adt/source/src/Force.cpp.s
.PHONY : home/pi/deps/adt/source/src/Force.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Force.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Force.cpp.s
.PHONY : home/pi/deps/adt/source/src/Force.cpp.s

home/pi/deps/adt/source/src/Length.o: home/pi/deps/adt/source/src/Length.cpp.o
.PHONY : home/pi/deps/adt/source/src/Length.o

# target to build an object file
home/pi/deps/adt/source/src/Length.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Length.cpp.o
.PHONY : home/pi/deps/adt/source/src/Length.cpp.o

home/pi/deps/adt/source/src/Length.i: home/pi/deps/adt/source/src/Length.cpp.i
.PHONY : home/pi/deps/adt/source/src/Length.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Length.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Length.cpp.i
.PHONY : home/pi/deps/adt/source/src/Length.cpp.i

home/pi/deps/adt/source/src/Length.s: home/pi/deps/adt/source/src/Length.cpp.s
.PHONY : home/pi/deps/adt/source/src/Length.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Length.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Length.cpp.s
.PHONY : home/pi/deps/adt/source/src/Length.cpp.s

home/pi/deps/adt/source/src/Mass.o: home/pi/deps/adt/source/src/Mass.cpp.o
.PHONY : home/pi/deps/adt/source/src/Mass.o

# target to build an object file
home/pi/deps/adt/source/src/Mass.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Mass.cpp.o
.PHONY : home/pi/deps/adt/source/src/Mass.cpp.o

home/pi/deps/adt/source/src/Mass.i: home/pi/deps/adt/source/src/Mass.cpp.i
.PHONY : home/pi/deps/adt/source/src/Mass.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Mass.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Mass.cpp.i
.PHONY : home/pi/deps/adt/source/src/Mass.cpp.i

home/pi/deps/adt/source/src/Mass.s: home/pi/deps/adt/source/src/Mass.cpp.s
.PHONY : home/pi/deps/adt/source/src/Mass.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Mass.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Mass.cpp.s
.PHONY : home/pi/deps/adt/source/src/Mass.cpp.s

home/pi/deps/adt/source/src/Moment.o: home/pi/deps/adt/source/src/Moment.cpp.o
.PHONY : home/pi/deps/adt/source/src/Moment.o

# target to build an object file
home/pi/deps/adt/source/src/Moment.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Moment.cpp.o
.PHONY : home/pi/deps/adt/source/src/Moment.cpp.o

home/pi/deps/adt/source/src/Moment.i: home/pi/deps/adt/source/src/Moment.cpp.i
.PHONY : home/pi/deps/adt/source/src/Moment.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Moment.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Moment.cpp.i
.PHONY : home/pi/deps/adt/source/src/Moment.cpp.i

home/pi/deps/adt/source/src/Moment.s: home/pi/deps/adt/source/src/Moment.cpp.s
.PHONY : home/pi/deps/adt/source/src/Moment.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Moment.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Moment.cpp.s
.PHONY : home/pi/deps/adt/source/src/Moment.cpp.s

home/pi/deps/adt/source/src/Rotation.o: home/pi/deps/adt/source/src/Rotation.cpp.o
.PHONY : home/pi/deps/adt/source/src/Rotation.o

# target to build an object file
home/pi/deps/adt/source/src/Rotation.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Rotation.cpp.o
.PHONY : home/pi/deps/adt/source/src/Rotation.cpp.o

home/pi/deps/adt/source/src/Rotation.i: home/pi/deps/adt/source/src/Rotation.cpp.i
.PHONY : home/pi/deps/adt/source/src/Rotation.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Rotation.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Rotation.cpp.i
.PHONY : home/pi/deps/adt/source/src/Rotation.cpp.i

home/pi/deps/adt/source/src/Rotation.s: home/pi/deps/adt/source/src/Rotation.cpp.s
.PHONY : home/pi/deps/adt/source/src/Rotation.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Rotation.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Rotation.cpp.s
.PHONY : home/pi/deps/adt/source/src/Rotation.cpp.s

home/pi/deps/adt/source/src/Speed.o: home/pi/deps/adt/source/src/Speed.cpp.o
.PHONY : home/pi/deps/adt/source/src/Speed.o

# target to build an object file
home/pi/deps/adt/source/src/Speed.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Speed.cpp.o
.PHONY : home/pi/deps/adt/source/src/Speed.cpp.o

home/pi/deps/adt/source/src/Speed.i: home/pi/deps/adt/source/src/Speed.cpp.i
.PHONY : home/pi/deps/adt/source/src/Speed.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Speed.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Speed.cpp.i
.PHONY : home/pi/deps/adt/source/src/Speed.cpp.i

home/pi/deps/adt/source/src/Speed.s: home/pi/deps/adt/source/src/Speed.cpp.s
.PHONY : home/pi/deps/adt/source/src/Speed.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Speed.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Speed.cpp.s
.PHONY : home/pi/deps/adt/source/src/Speed.cpp.s

home/pi/deps/adt/source/src/Translation.o: home/pi/deps/adt/source/src/Translation.cpp.o
.PHONY : home/pi/deps/adt/source/src/Translation.o

# target to build an object file
home/pi/deps/adt/source/src/Translation.cpp.o:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Translation.cpp.o
.PHONY : home/pi/deps/adt/source/src/Translation.cpp.o

home/pi/deps/adt/source/src/Translation.i: home/pi/deps/adt/source/src/Translation.cpp.i
.PHONY : home/pi/deps/adt/source/src/Translation.i

# target to preprocess a source file
home/pi/deps/adt/source/src/Translation.cpp.i:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Translation.cpp.i
.PHONY : home/pi/deps/adt/source/src/Translation.cpp.i

home/pi/deps/adt/source/src/Translation.s: home/pi/deps/adt/source/src/Translation.cpp.s
.PHONY : home/pi/deps/adt/source/src/Translation.s

# target to generate assembly for a file
home/pi/deps/adt/source/src/Translation.cpp.s:
	$(MAKE) -f CMakeFiles/VideoTags.dir/build.make CMakeFiles/VideoTags.dir/home/pi/deps/adt/source/src/Translation.cpp.s
.PHONY : home/pi/deps/adt/source/src/Translation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... VideoTags"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Source/src/VideoTag.o"
	@echo "... Source/src/VideoTag.i"
	@echo "... Source/src/VideoTag.s"
	@echo "... home/pi/deps/AprilTags/Edge.o"
	@echo "... home/pi/deps/AprilTags/Edge.i"
	@echo "... home/pi/deps/AprilTags/Edge.s"
	@echo "... home/pi/deps/AprilTags/FloatImage.o"
	@echo "... home/pi/deps/AprilTags/FloatImage.i"
	@echo "... home/pi/deps/AprilTags/FloatImage.s"
	@echo "... home/pi/deps/AprilTags/GLine2D.o"
	@echo "... home/pi/deps/AprilTags/GLine2D.i"
	@echo "... home/pi/deps/AprilTags/GLine2D.s"
	@echo "... home/pi/deps/AprilTags/GLineSegment2D.o"
	@echo "... home/pi/deps/AprilTags/GLineSegment2D.i"
	@echo "... home/pi/deps/AprilTags/GLineSegment2D.s"
	@echo "... home/pi/deps/AprilTags/Gaussian.o"
	@echo "... home/pi/deps/AprilTags/Gaussian.i"
	@echo "... home/pi/deps/AprilTags/Gaussian.s"
	@echo "... home/pi/deps/AprilTags/GrayModel.o"
	@echo "... home/pi/deps/AprilTags/GrayModel.i"
	@echo "... home/pi/deps/AprilTags/GrayModel.s"
	@echo "... home/pi/deps/AprilTags/Homography33.o"
	@echo "... home/pi/deps/AprilTags/Homography33.i"
	@echo "... home/pi/deps/AprilTags/Homography33.s"
	@echo "... home/pi/deps/AprilTags/MathUtil.o"
	@echo "... home/pi/deps/AprilTags/MathUtil.i"
	@echo "... home/pi/deps/AprilTags/MathUtil.s"
	@echo "... home/pi/deps/AprilTags/Quad.o"
	@echo "... home/pi/deps/AprilTags/Quad.i"
	@echo "... home/pi/deps/AprilTags/Quad.s"
	@echo "... home/pi/deps/AprilTags/Segment.o"
	@echo "... home/pi/deps/AprilTags/Segment.i"
	@echo "... home/pi/deps/AprilTags/Segment.s"
	@echo "... home/pi/deps/AprilTags/TagDetection.o"
	@echo "... home/pi/deps/AprilTags/TagDetection.i"
	@echo "... home/pi/deps/AprilTags/TagDetection.s"
	@echo "... home/pi/deps/AprilTags/TagDetector.o"
	@echo "... home/pi/deps/AprilTags/TagDetector.i"
	@echo "... home/pi/deps/AprilTags/TagDetector.s"
	@echo "... home/pi/deps/AprilTags/TagFamily.o"
	@echo "... home/pi/deps/AprilTags/TagFamily.i"
	@echo "... home/pi/deps/AprilTags/TagFamily.s"
	@echo "... home/pi/deps/AprilTags/UnionFindSimple.o"
	@echo "... home/pi/deps/AprilTags/UnionFindSimple.i"
	@echo "... home/pi/deps/AprilTags/UnionFindSimple.s"
	@echo "... home/pi/deps/adt/source/src/Acceleration.o"
	@echo "... home/pi/deps/adt/source/src/Acceleration.i"
	@echo "... home/pi/deps/adt/source/src/Acceleration.s"
	@echo "... home/pi/deps/adt/source/src/Angle.o"
	@echo "... home/pi/deps/adt/source/src/Angle.i"
	@echo "... home/pi/deps/adt/source/src/Angle.s"
	@echo "... home/pi/deps/adt/source/src/Attitude.o"
	@echo "... home/pi/deps/adt/source/src/Attitude.i"
	@echo "... home/pi/deps/adt/source/src/Attitude.s"
	@echo "... home/pi/deps/adt/source/src/Box.o"
	@echo "... home/pi/deps/adt/source/src/Box.i"
	@echo "... home/pi/deps/adt/source/src/Box.s"
	@echo "... home/pi/deps/adt/source/src/Coordinate.o"
	@echo "... home/pi/deps/adt/source/src/Coordinate.i"
	@echo "... home/pi/deps/adt/source/src/Coordinate.s"
	@echo "... home/pi/deps/adt/source/src/Duration.o"
	@echo "... home/pi/deps/adt/source/src/Duration.i"
	@echo "... home/pi/deps/adt/source/src/Duration.s"
	@echo "... home/pi/deps/adt/source/src/Force.o"
	@echo "... home/pi/deps/adt/source/src/Force.i"
	@echo "... home/pi/deps/adt/source/src/Force.s"
	@echo "... home/pi/deps/adt/source/src/Length.o"
	@echo "... home/pi/deps/adt/source/src/Length.i"
	@echo "... home/pi/deps/adt/source/src/Length.s"
	@echo "... home/pi/deps/adt/source/src/Mass.o"
	@echo "... home/pi/deps/adt/source/src/Mass.i"
	@echo "... home/pi/deps/adt/source/src/Mass.s"
	@echo "... home/pi/deps/adt/source/src/Moment.o"
	@echo "... home/pi/deps/adt/source/src/Moment.i"
	@echo "... home/pi/deps/adt/source/src/Moment.s"
	@echo "... home/pi/deps/adt/source/src/Rotation.o"
	@echo "... home/pi/deps/adt/source/src/Rotation.i"
	@echo "... home/pi/deps/adt/source/src/Rotation.s"
	@echo "... home/pi/deps/adt/source/src/Speed.o"
	@echo "... home/pi/deps/adt/source/src/Speed.i"
	@echo "... home/pi/deps/adt/source/src/Speed.s"
	@echo "... home/pi/deps/adt/source/src/Translation.o"
	@echo "... home/pi/deps/adt/source/src/Translation.i"
	@echo "... home/pi/deps/adt/source/src/Translation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

